### ISSUE TITLE
Using CSS Animations to detect element resize, instead of global window.resize event?

### ISSUE THREAD

**Issue by acdlite** [souporserious/react-measure#1]
Cool project!

A downside to re-computing dimensions on `window.resize` events is that it doesn't account for the other ways in which an element's dimensions might have changed. Have you considered using something like [javascript-detect-element-resize](https://github.com/sdecima/javascript-detect-element-resize), which detects resize using `animationStart` events? https://github.com/sdecima/javascript-detect-element-resize/blob/master/detect-element-resize.js#L116-L131

I can't personally vouch for this approach because I've never used it, but it sounds like a good idea in theory :)

**Comment by souporserious** [comment]
This is cool! Going to check it out. I'll leave this issue open until I decide whether or not to bring it in. Thanks for the find :)

**Comment by souporserious** [comment]
Closing this, I worked on integrating it last night, but ultimately feel that this should be up to the user to integrate as needed. Appreciate the feedback though!
