### ISSUE TITLE
resizeObserver not correctly disconnected in componentWillUnmount in version 2.0.0

### ISSUE THREAD

**Issue by siirila** [souporserious/react-measure#108]
In version 2.0.0, the resize observer is not correctly disconnected during the componentWillUnmount lifecycle hook. It checks for this.resizeObserver to see if an observer exists to disconnect, but it should be checking this._resizeObserver. See https://github.com/souporserious/react-measure/blob/a5a56a60dfdb1c2c62e980641b6b317efca3ed0f/src/with-content-rect.js#L57

This is causing errors when a measured component is unmounted and the resize observer tries to measure the size of a null element after it is unmounted.

This is a really simple fix, and I would issue a pull request myself, but it looks like with the redesign this code no longer exists. Is there a way to get a fix for this issue included in a new release?

**Comment by souporserious** [comment]
🤦‍♂️  If you would like to submit a PR I can cut a release under version 2, not sure how this wasn't found earlier 😓, sorry about that. It has been fixed properly in version 3 that's coming out soon.

**Comment by mbueti** [comment]
Is there any update on this? v3 is as of yet unreleased, and this bug is creating a huge amount of noise in our exception handling.

**Comment by souporserious** [comment]
Sorry, I haven't had any free time to devote to this, I will be soon, but I'm not sure exactly when. If you would like to submit a PR for V2 fixing this, I will review it and publish a patch if all looks well.

**Comment by mbueti** [comment]
There you go! https://github.com/souporserious/react-measure/pull/112
