### ISSUE TITLE
@babel/runtime is not a dev dependency

### ISSUE THREAD

**Issue by julioolvr** [souporserious/react-measure#123]
In a project with Babel 6 and Webpack 3, trying to use `react-measure` throws several errors like:

```
ERROR in ./node_modules/react-measure/dist/index.esm.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/joliv/Dev/website/node_modules/react-measure/dist'
```

`dist/index.esm.js` does try to import stuff from `@babel/runtime` but that seems to be a transitive dev dependency of the project, so I'd expect it not to be referenced by build artifacts. That being said I could be wrong - I'm not sure what are common expectations, but it feels that if Babel 7 were required to use the project then `@babel` shouldn't be a dev dependency.

For the time being, I'm still testing this out but `npm add @babel/runtime` seems to be working and is playing well with having Babel 6 in the same project so far.

**Comment by souporserious** [comment]
Oops! Sorry about that 😅. It should be fixed under `v2.2.2`. Please feel free to reopen if there are any further issues. Thanks for filing an issue! 🙏

**Comment by ahmedsharif** [comment]
I am facing the same issue  that @julioolvr posted last time. I follow your solution and down-grade react-measure version to 2.2.1 but it still give me same error.  
![babel_error](https://user-images.githubusercontent.com/17411512/51731648-7c5dff00-209d-11e9-9ab6-d9aef0509b09.PNG)

**Comment by souporserious** [comment]
Hmm weird 🤔 this should be fixed in the latest version. @ahmedsharif does this error occur with `v2.2.2` installed?

**Comment by ahmedsharif** [comment]
Yes. I tried these versions v2.2.2 v2.2.1 and v2.2.3. Can you kindly help me regarding this issue?

**Comment by souporserious** [comment]
@ahmedsharif I just got back from vacation so I have some things to catch up on, but I will look into this as soon as I get a chance. Please feel free to submit a PR if you come across a solution. I might try updating `@babel/runtime` to see if that helps anything.
