### ISSUE TITLE
ResizeObserver entries are undefined when measure method is called

### ISSUE THREAD

**Issue by piecyk** [souporserious/react-measure#124]
This was introduced with https://github.com/souporserious/react-measure/commit/446e3e8281b86a0e81438424ca39ca121ad7418f 
as `measure` method is missing the entires from ResizeObserver callback 

```js
_resizeObserver = new ResizeObserver(() => {
  this.measure()
})
```

**Comment by vineetkumar1511** [comment]
We are also facing this issue. They have forgot to pass arguments here. Also this can we done in very clean way.
