### ISSUE TITLE
accurateHeight doesn't work on flex containers

### ISSUE THREAD

**Issue by jedwards1211** [souporserious/react-measure#13]
I don't have a minimal repo scenario for this yet.
The element resize detection seems fairly hacky and I don't trust it completely.  I'd think we should respond to window resize events (throttled to 1 sec or so) as a failsafe mechanism.

Here's a snippet of my code (`onPlotResize` sets the value of `plotWidth` and `plotHeight`):

``` es6
    <Measure onMeasure={onPlotResize}>
      <div className="mf-DeviceHomeView-plot-canvas">
        <AxialPlotInteraction domainAxis={timeAxis} domainConversion={domainMetrics.conversion}>
          <Canvas width={plotWidth} height={plotHeight}>
            <CanvasClearer />
            <GridLines axis={valueAxis} metrics={valueMetrics} />
            <GridLines axis={timeAxis} metrics={domainMetrics} />
            <Trace
                domainAxis={timeAxis}
                domainConversion={domainMetrics.conversion}
                points={points}
                valueConversion={valueConversion}
                currentTime={currentTime}
            />
          </Canvas>
        </AxialPlotInteraction>
      </div>
    </Measure>
```

Here's the element in the browser:
![screen shot 2016-07-29 at 3 40 35 pm](https://cloud.githubusercontent.com/assets/1448194/17262729/d6602f8c-55a2-11e6-8cd3-11728d9012cf.png)

**Comment by souporserious** [comment]
If you can get it sandboxed in a [codepen](http://codepen.io/) that would be awesome. Or even your own PR that has the code works as well. I'm wondering if it has to do with it being a canvas element.

@wnr are there any known issues with canvas and element-resize-detector?

**Comment by jedwards1211** [comment]
Argh nevermind, I think the problem was just that I'm not restricting the width of the div if the canvas inside is wider than the screen, and so the `div` itself isn't shrinking.

**Comment by jedwards1211** [comment]
well, erm...still not sure.  Some interaction of flexbox, overflow: hidden and canvas is causing this...

**Comment by jedwards1211** [comment]
Uhhh...now it's measuring my div height as 170 even though it's got `height: 170px; overflow: hidden`.

**Comment by jedwards1211** [comment]
Okay here's what threw me for a loop: http://codepen.io/jedwards1211/pen/OXwmAJ

The top-level `display: flex` div has `width: 200px` yet the inner div `flex: 1 1 200px` expands to the full canvas width of `300`.

**Comment by jedwards1211** [comment]
Happens even if I replace the `canvas` with `div`.  Sigh... you would have at least hoped that flexbox is completely predictable, but I guess it isn't.

**Comment by souporserious** [comment]
I've seen this issue before on another library that uses React Measure. For some reason containers with `display: flex` are hard to get an accurate height. I need to look into how to get proper dimensions. It might be the [clone](https://github.com/souporserious/react-measure/blob/master/src/get-clone-dimensions.js) that messes something up when it measures it.

**Comment by souporserious** [comment]
Ah yeah I think it has to do with the cloning when using `accurateHeight`. I'll look into this.

**Comment by jedwards1211** [comment]
Okay, I was actually accidentally triggering `accurateHeight` in my branch where I was responding to window `resize` events, haha.  But in any case we should rename the issue

**Comment by asvetliakov** [comment]
@souporserious 
I've similar problem with nested accordions, height change in nested element is not going to be picked up by parent element, see nested accordion example in: https://hallister.github.io/semantic-react/#!/Accordion
I think it used to work before upgrading to 0.4.\* versions.

**Comment by souporserious** [comment]
@asvetliakov I actually released an auto height component a couple of days ago that handles nested height without any noticeable issues https://github.com/souporserious/react-fluid-container maybe you can get some ideas for your lib from there. Still looking into a better way to get accurate height measurements with flex items though.

**Comment by souporserious** [comment]
@jedwards1211 @asvetliakov I moved the dimension calculation into its own repo [here](https://github.com/souporserious/get-node-dimensions) I updated react-measure with the latest version and tested flexbox and tests currently pass. Please let me know if you have anymore issues. Feel free to file any dimension related issues in that new repo.
