### ISSUE TITLE
Exception when changing key of rendered child

### ISSUE THREAD

**Issue by danielberndt** [souporserious/react-measure#19]
First off, thanks for this wonderful library! I'm quite glad I've found it since I've been doing way too much manual dimension measuring. I especially like the child-as-a-fn based approach!

Anyhow, here's an issue I came across: when rendering a child with a different key from the previous one, the new child won't get properly assigned as the new `this._node`.

So basically [this line](https://github.com/souporserious/react-measure/blob/master/src/Measure.jsx#L45) needs to somehow be applied once the node changes. I guess using the [ref-callback](https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute) might be an appropriate tool here?

Here's some sample code which exhibits the issue

``` jsx
<Measure whiteList={['width']}>{({width}) => 
  !width ? <div key="empty" style={{height: 1}}/> : <div key="with-width" style={{height: 20}}/>
}</Measure>
```

**Comment by souporserious** [comment]
Thank you for the kind words! Yeah measuring became a pain, so it inspired me to write this :) glad to hear it's helping you out!

Thank you for providing example code. It has been fixed here https://github.com/souporserious/react-measure/commit/ef917f926502814b58d45a01355a9969d8d161b4 and is out in the latest release 🎉

**Comment by danielberndt** [comment]
Thanks for this super fast fix! I really appreciate it :)

I like the simplicity of your solution, but it makes the hidden assumption that a detached node will not be recycled and attached to other parts of the dom. Once react starts doing this, this will lead to presumably very weird behaviour. This is why using ref callbacks might be a safer approach since it uses an official react-contract for getting the correct node for a component.

I think this whole issue is quite edge case-ish, so I'm personally not too bothered. But if weird things should happen, this might be one thing to look for :)

**Comment by souporserious** [comment]
Totally. I was going to implement a ref callback and realized why I hadn't before https://github.com/souporserious/react-measure/blob/master/src/Measure.jsx#L129 I'm not sure I can use a ref callback since I'm allowing child functions, maybe I can somehow? I'm not sure.
