### ISSUE TITLE
"resizeDetector is not defined" error on componentWillUnmount

### ISSUE THREAD

**Issue by andrewhathaway** [souporserious/react-measure#21]
I'm getting a `Uncaught ReferenceError: resizeDetector is not defined` exception when unmounting a component from the view. I'm using the child function usage. Having checked the source, there doesn't seem to be any reference of the `resizeDetector` apart from within that method.

**Comment by souporserious** [comment]
Fixed here https://github.com/souporserious/react-measure/pull/23
