### ISSUE TITLE
Uncaught ReferenceError: resizeDetector is not defined

### ISSUE THREAD

**Issue by alex-golovanov** [souporserious/react-measure#22]
Is the error I get after upgrading from 1.3.1 to 1.4.0.

`key: 'componentWillUnmount',
  value: function componentWillUnmount() {
      resizeDetector().removeAllListeners(this._node);
      resizeDetector().uninstall(this._node);
      this._node = null;
 }`

**Comment by souporserious** [comment]
Fixed here https://github.com/souporserious/react-measure/pull/23
