### ISSUE TITLE
1.4.0 breaks server rendering

### ISSUE THREAD

**Issue by joeruello** [souporserious/react-measure#24]
Hi! Amazing component!

Not sure if I should raise this in [resize-observer-polyfill](https://github.com/que-etc/resize-observer-polyfill) or here, but it seems they have a reference to `window` which breaks running react-measure while server rendering. 

If you're willing, happy to open a PR here to check if window exists before registering the observer, or ask in the polyfill repo. Worst case I can make my component server aware, but would rather keep it agnostic.

Meanwhile will stay at 1.3.1 

Thanks!

**Comment by souporserious** [comment]
Sorry about that! I just fixed the issue over [here](https://github.com/souporserious/react-view-pager/issues/39). I'll get a fix out ASAP.

**Comment by souporserious** [comment]
Alright, should be fixed with this https://github.com/souporserious/react-measure/commit/8e568265d95a6014a9f45506b6ae4d3b4833c3b1 and is out in the latest release. Please feel free to reopen if this did not fix your problem. Sorry for any inconveniences.
