### ISSUE TITLE
onMeasure not triggering on every render.

### ISSUE THREAD

**Issue by achobanov** [souporserious/react-measure#26]
Neat plugin, but I don't understand when exactly does onMeasure fire. From what I gather it should trigger on every render, yet I am having a case when I click on item, it changes state, which invokes render, but onMeasure is not triggered. Then if I click on another item, it invokes the same change of state, via the same exact function, executed with same context and no properties, it changes state, invoking render and onMeasure fires up. This happens consistently for the certain items. it's not random at all, and that makes it very weird, but the problem is not in my items, since both of them receive as props the same exact function.

**Comment by souporserious** [comment]
Hello 👋 `onMeasure` will only fire when the `measure` method is called. The component is hooked up to a [`ResizeObserver`](https://github.com/que-etc/resize-observer-polyfill) and will call `measure` when the dimensions of your component have changed. You can call that manually if you need to by using refs `this.measureComponent.measure()`. Does that make sense?

**Comment by achobanov** [comment]
Alright, that sounds good. I will try to call it manually when I need it then. Would you wirte something like that in the Readme? I think it would help people, especially unexperienced, like myself, to knon when and how onMeasure is called. If this doesn't work, could I PM you or something for a more detailed explanation of my problem, beause I don't know who else can help me out with measure. Thanks

**Comment by souporserious** [comment]
Yes, absolutely :) your feedback helps. I will leave this open until I add more to the README. Have you heard of [Reactiflux](http://www.reactiflux.com/)? I'm usually hanging around there. I can try and help with any issues you have.

**Comment by achobanov** [comment]
Hi back. I must have misunderstood something, because I can't get it to measure manually with `this.measureComponent.measure()`. It says measureComponent is undefined. What did I miss?

**Comment by souporserious** [comment]
Is `this.measureComponent` coming from refs? Maybe some more context would help. Can you paste what you have?

I just realized I do this in the example folder, you can see it here: https://github.com/souporserious/react-measure/blob/master/example/index.jsx#L57-L63

**Comment by achobanov** [comment]
I looked at the example. I understand the arrow function to `onClick` listener , but I dont really get what's going on inside the `ref`. Also I would like to fire up measure inside `componentDidMount` and `componentDidUpdate`. Also another read through your `Readme` got my attention to `useClone` prop. Can that be used to measure the proper width of `element` wider then the `document`?

**Comment by souporserious** [comment]
We're assigning the component that is returned in the ref callback function as a property. More on ref callbacks [here](https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute). Pretty much we just want access to that component's methods, which in this case is `measure`.

Is this what you are looking to do?
```
class ComponentToMeasure extends Component {
  componentDidMount() {
    this.measureComponent.measure()
  }

  render() {
    return (
      <Measure
        ref={(component) => {
          this.measureComponent = component
        }}
      >
        <div>
          content...
        </div>
      </Measure>
    )
  }
}
```
Also, be careful not to use `setState` in `onMeasure`. If you are calling `measure` in `componentDidUpdate` you will get caught in an infinite loop.

As for `useClone` that is useful for elements that may be collapsed and have a width or height of 0, as well as hidden elements. It sounds like you need to get the `scrollWidth`. More on that [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollWidth). We don't pass that back right now, but that should be easy to add to the payload sent back.

**Comment by achobanov** [comment]
Okey I managed to fire `measure()` but that didn't fix my problem. Apparently it is not related to measure, but could you take a look at `git`, because I really can't explain whatever is going on: https://github.com/teamRPA/React-Family. If you'd like we could go over discord, because this is not directly  related to measure and certainly it's not measure issue, so I don't know if it has any place in its issues ;D. You should take a look under` src/components/FamilyTree`,` TreeNode` and `src/views/FamilyTreeVIew`. If you want to run it, add /tree to your localhost to view the tree. Then you can click on any `person`, and then click ouside of the popup to remove it. I want the tree to render without reordering any nodes to fit inside the screen. Thanks :)

**Comment by achobanov** [comment]
Hello again. I have finally found my mistake. The thing is that my `html` and `css` are structured in such a way that it if I click the first item my component's width didn't change, but if I clicked the second - then it shortens a little. I am not still sure how to work around this, but at least I know the problem now. What's up with `scrollWidth`?

**Comment by souporserious** [comment]
It's a little hard for me to help without seeing the code. Is it possible you can fork this [Codepen](http://codepen.io/souporserious/pen/rLdwao/?editors=0010) and show your problem there? That way I'll be able to help as best I can 😃

**Comment by achobanov** [comment]
Don't you see the code from the repo I shared? However I have solved my issue, so I think I'm going to close this. Thanks for your time and help :) Great plugin! Cheers!
