### ISSUE TITLE
Uncaught TypeError: ResizeObserver is not a constructor

### ISSUE THREAD

**Issue by asterikx** [souporserious/react-measure#27]
Hi,

I just run into a problem using react-measure in combination with Webpack 2.x. I get the error message `Measure.js:109: Uncaught TypeError: ResizeObserver is not a constructor(…)`. With older versions  of Webpack (tested with v1.12.2) there seems to be no issue at all.

A basic project setup for reproducing the error can be found [here](https://github.com/mulles3008/ReactMeasure-ResizeObserverTypeError).

I hope you can help me with this :)

**Comment by souporserious** [comment]
Hello,

Sorry, I'm unfamiliar with how Webpack 2 bundles modules :( I haven't had a chance to play with it yet. Please let me know if you find a fix. I will leave this open in case anyone can help.

**Comment by asterikx** [comment]
[This](http://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x?answertab=active#tab-top) entry on StackOverflow explains the problem.
`require('resize-observer-polyfill').default` solves my issue. Tested with Webpack v.1.12.2 and v.2.1.0-beta.27 (latest version). PR coming ;)

**Comment by souporserious** [comment]
Thanks for the PR! The fix has been published to NPM :) https://github.com/souporserious/react-measure/commit/76a79f2ff4bdb93297247cef404742fb6989591f

**Comment by gcrabtree** [comment]
@souporserious That was a quick response, but that fix breaks for people using Webpack 1.14...
Reverting the change appears to work. Looks like you need to test whether .default is available or not.
