### ISSUE TITLE
ResizeObserver Polyfill creates errors with Webpack & UglifyJS

### ISSUE THREAD

**Issue by terencechow** [souporserious/react-measure#29]
New dev on the team tried to npm install our package.json and got the following error:

    ERROR in bundle.js from UglifyJs
    SyntaxError: Unexpected token: punc ()) [bundle.js:33478,18] 

We had `react-measure: "^1.3.1"` in `package.json` and the caret made it upgrade to `1.4.x` when that was released.

Looks like 1.4.x uses ResizeObserver polyfill which created the above error when webpack & uglifyjs are bundling. Technically you would be okay if you were to use uglifyjs harmony branch but since I don't want to fork webpack and subsequently modify the fork's package json, it's easier to just pin `react-measure` to 1.3.1 to solve this. 

Putting this here in case anyone else comes across it and something that you might want to think about since lotsa ppl use react with webpack and uglify in production.

**Comment by souporserious** [comment]
Sorry about that 😞  Is there anything we can do to fix this? Or maybe it is an issue in the polyfill library?

Thinking more about it and wondering what's causing this. I'm using UglifyJS for the demo build here https://github.com/souporserious/react-measure/blob/master/webpack.config.js#L37-L49 and it seems fine. Maybe I'm missing something.

**Comment by terencechow** [comment]
Might be because I'm using webpack 2 beta?

**Comment by thebuilder** [comment]
Also getting a ResizeObserver error - Running Webpack 2:

```
scripts/0-d1a73d3a1dcc35893472.chunk.js from UglifyJs
SyntaxError: Unexpected token: name (ResizeObserver) [./~/resize-observer-polyfill/index.js:3,0][scripts/0-d1a73d3a1dcc35893472.chunk.js:2526,4]
```

**Comment by souporserious** [comment]
Sorry, I'm not sure what is causing this 😞  I wish I could help. Please feel free to create a PR if you find a solution.

**Comment by robwise** [comment]
I got the first guy's error (`SyntaxError: Unexpected token: punc ())`), then I changed by babel-loader to not exclude node-modules, and then I got the second guy's error (`SyntaxError: Unexpected token: name (ResizeObserver)`).

**Comment by robwise** [comment]
I was able to get around this by not using `exclude` or `include` with my Webpack babel-loader. I believe what's going on is that this library is ES6 code and the Uglifier plugin is having trouble parsing it for whatever reason. Running the package through babel seems to fix the issue.

**Comment by que-etc** [comment]
This and #27 issues were caused by the `module` field in the package file which pointed to a es6 version of the polyfill. I've removed it and now Webpack 2 takes the es5 umd bundle which always exports the ResizeObserver constructor instead of an object with the `default` property. 

I've also added a fallback for a non-browser environment which fixes the server rendering problem described in #24.

These changes are available in v 1.3.1 and I believe that now you can remove [all](https://github.com/souporserious/react-measure/blob/master/src/Measure.jsx#L7) of [those](https://github.com/souporserious/react-measure/blob/master/src/Measure.jsx#L57) conditions.

Guys, I'm really sorry about this mess. Why you didn't tell me about those problems in the first place? I would have fixed them long ago.

**Comment by souporserious** [comment]
Out in the latest [release](https://github.com/souporserious/react-measure/commit/204b8bb2f784315528d2aa647247ecd5dd0f1a6e). Thanks @que-etc! I appreciate the help. I was unaware it was your library that was causing the issue. I thought it had something to do with what I was doing.

Please feel free to re-open this if the issue still occurs.

**Comment by marcandrews** [comment]
I am trying to use react-measure@1.4.5 with [react-boilerplate@3.3.3](https://github.com/mxstbr/react-boilerplate) and I am getting the following error when running the development server:

```
Uncaught (in promise) TypeError: _resizeObserverPolyfill2.default is not a constructor
    at Measure.componentDidMount (eval at ./node_modules/react-measure/lib/Measure.js (0.chunk.js:278), <anonymous>:105:29)
    at eval (ReactCompositeComponent.js:264)
    at measureLifeCyclePerf (ReactCompositeComponent.js:74)
    at eval (ReactCompositeComponent.js:263)
    at CallbackQueue.notifyAll (CallbackQueue.js:67)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:81)
    at ReactReconcileTransaction.closeAll (Transaction.js:204)
    at ReactReconcileTransaction.perform (Transaction.js:151)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:138)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:90)
```

Is this error related to this issue?

Sorry, I'm still new to React/Babel/Webpack2, but is there any additional information you need to help me solve this issue?

**Comment by souporserious** [comment]
@que-etc any idea on the above?

**Comment by que-etc** [comment]
Still tackling this problem but for now I found that v. 3.4.0 works fine. My take is that it has something to do with webpack@2.1.0-beta.25 which is used in the earlier version of react-boilerplate.

Yeap, fixed in webpack@2.2.0-rc.0 (https://github.com/webpack/webpack/issues/3168)

**Comment by que-etc** [comment]
@marcandrews would you please try updating to webpack 2.2?

**Comment by marcandrews** [comment]
@que-etc @souporserious giving it a try now and will report back. Thanks.

**Comment by marcandrews** [comment]
Updated to webpack@2.2.0-rc.3 and seems like everything is working. Thanks for the help!

**Comment by souporserious** [comment]
Thanks for the help @que-etc 🎉

**Comment by designbyadrian** [comment]
Was running Webpack 2.1.0-beta.25. Updating to ^2.2.0 *(2.2.1 at the time of writing)* fixed my problem.
