### ISSUE TITLE
Whitelist & blacklist  don't appear to function as expected

### ISSUE THREAD

**Issue by newtriks** [souporserious/react-measure#30]
Providing an array of properties to either whitelist or blacklist (as shown [here in your docs](https://github.com/souporserious/react-measure#whitelist-proptypesarray)) doesn't appear to work. 

If you look at this [example](http://codepen.io/anon/pen/vyQbqy) based on yours, it would appear all the properties are still getting included both on initial measure and on further resizes?

Is this a bug or am I missing something?

**Comment by souporserious** [comment]
`whitelist` and `blacklist` are what determines when `onMeasure` should fire. So if you have `whitelist={['height]}`, it will only fire `onMeasure` when the `height` changes, rather than every property. Does that make sense? I don't explain that very well in the README, sorry about that :/

**Comment by newtriks** [comment]
Ahhh hah! Okay yes that makes sense now, thank you.

**Comment by souporserious** [comment]
Awesome! Sorry for the misunderstanding. I updated the docs to be more clear :) https://github.com/souporserious/react-measure/commit/e05dcdeea14679db939283144c76c3587e224fd6
