### ISSUE TITLE
_resizeObserverPolyfill2.default is not a constructor

### ISSUE THREAD

**Issue by designbyadrian** [souporserious/react-measure#32]
Getting this error in my Chrome console:

```
Uncaught (in promise) TypeError: _resizeObserverPolyfill2.default is not a constructor
    at Measure.componentDidMount (eval at ./node_modules/react-measure/lib/Measure.js (0.chunk.js:159), <anonymous>:105:29)
    at eval (ReactCompositeComponent.js:264)
etc...
```

Simplified JS:

```javascript
import React from 'react';
import Measure from 'react-measure';

export default class Folder extends React.Component {
  constructor(props) {
    super(props);
    this.onMeasure = this.onMeasure.bind(this); // I need this.props later
  }

  onMeasure(dimensions) {
    console.log("onMeasure",dimensions,this);
  }

  render() {
  
   const items = (<div/>);

    return (
      <Measure onMeasure={this.onMeasure} whitelist={['width']}>
        <div>
          {items}
        </div>
      </Measure>
    );
  }
}
```

I added "resize-observer-polyfill" to package.json, but notice no difference.

**Comment by que-etc** [comment]
I believe that it's the same issue https://github.com/souporserious/react-measure/issues/29#issuecomment-272659453. May I ask if you are using Webpack 2.1-beta? If it's so, then would please update to 2.2.x?

**Comment by designbyadrian** [comment]
I apologise for not looking in the closed issues section! How very lazy of me. I'll continue over there in case I still have issues. Thank you.

**Comment by souporserious** [comment]
Thanks for responding so quick @que-etc! And glad you were able to figure it out @designbyadrian! Would it be helpful to point to this in the README section?
