### ISSUE TITLE
There can only be one

### ISSUE THREAD

**Issue by martinwebrant** [souporserious/react-measure#33]
It does not trigger changes if you nest components. I think you use the resize-observer-polyfill wrong, looks like it wants to have one instance only.

**Comment by que-etc** [comment]
@martinwebrant  Well, for all I know there is no such limitation. Could you please post a small sample to reproduce the problem? I've tried adding a nested Measure component to [this sample](http://codepen.io/souporserious/pen/rLdwao/) and it worked fine.

**Update:** [nested measure component](http://codepen.io/anon/pen/GrPebV).

**Comment by souporserious** [comment]
Thanks for the help again @que-etc :)

@martinwebrant is it possible you can produce a Codepen showing the bug?

I use React Measure in [React Fluid Container](https://github.com/souporserious/react-fluid-container) and am able to have nested height calculations. Haven't seen any issues so far. Maybe it's a browser specific bug?

**Comment by martinwebrant** [comment]
Sorry, my bad jumping to conclusions. Should had broken my code down first and posted a minimal repro before sending you on to a wild goose chase. I'll get back with a proper report.

**Comment by souporserious** [comment]
No worries. Please let me know if you find anything and I'll look into it 😃

**Comment by que-etc** [comment]
@martinwebrant I think I've pinned down the problem you are experiencing. Indeed, there might be a conflict between multiple instances of the ResizeObserver when their callbacks affect content dimensions of each other elements. I've patched it in the [v1.4.1](https://github.com/que-etc/resize-observer-polyfill/releases/tag/1.4.1).

Could you please try to swap your local `./node_modules/resize-observer-polyfill/dist` folder with [this one](https://github.com/que-etc/resize-observer-polyfill/tree/master/dist) to see if it helps?
