### ISSUE TITLE
Not compatible with react native

### ISSUE THREAD

**Issue by JulianKingman** [souporserious/react-measure#34]
It would be great if this was compatible with react native, but currently gives the error `unable to resolve module react-dom`.

**Comment by souporserious** [comment]
Sorry, but I'm currently unfamiliar with React Native. Some things would need to be moved around and probably need a seperate build, but I'm open to any PR's or ideas you have :)

**Comment by JulianKingman** [comment]
After looking around and understanding a few things, I shouldn't have opened this issue in the first place :)

This package obviously works with `react-dom`, because it's a web component. React native by contrast works with native components. Also, the native `View` component has a method very similar API to what this package does, like so:
````jsx
<View onLayout={({nativeEvent}) => this.setState({height: nativeEvent.layout.height, width: nativeEvent.layout.width}))>{....}</View>
````
So although it would be easy to implement a wrapper for react native, there's not really even a point 😕
