### ISSUE TITLE
React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by silentpickle** [souporserious/react-measure#36]
I finally tried copy and pasting the example, and other than 'classNames' breaking, I'm sure I was doing everything exactly to the 'T'.   

Whether I had 1 child, or 0 children, I got this:

React.Children.only expected to receive a single React element child.

And in usage, I just stuck the 'Measure' around my previously working <div> object.   It would be super cool if this worked, but....

**Comment by silentpickle** [comment]
Stack trace for your amusement:

Uncaught Error: React.Children.only expected to receive a single React element child.
    at invariant (invariant.js:44)
    at Object.onlyChild [as only] (onlyChild.js:33)
    at Measure.render (Measure.js:162)
    at eval (ReactCompositeComponent.js:796)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:362)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)

**Comment by souporserious** [comment]
React Measure only works with one child. It looks like you might be passing multiple children? Can you please [fork this pen](http://codepen.io/souporserious/pen/rLdwao/) and create a reduced test case and I will look into it :)

**Comment by silentpickle** [comment]
While I will totally say there's probably 'other stuff wrong with my code' (because, there is. I'm trying the old school componentDidMount and my component which I totally have a legit ref to, returns a width,height,left,right,etc of '0')

http://codepen.io/davecrandall/pen/zZGXQM

Recreates a similar error.  No components in measure.   

Some background...  I'm embedding a component in backbone and it has its own 'this.el' that I'm attaching stuff to, and in general it's suspect, but it's worked so far.

**Comment by que-etc** [comment]
@silentpickle  There's got to be a mistake: your pen's identical to the source and it doesn't throw exceptions (checked in Chrome, FF and IE).

Oh, it looks like it's been updated and now the Measure component doesn't have a child element.

**Comment by silentpickle** [comment]
Apologies, codepen is beyond me...  I didn't hit 'save', then I broke it and hit save.  Moondays.

Here's a new one

http://codepen.io/davecrandall/pen/JWdQeO

Basically if you have an empty '<Measure></Measure>' it didn't work really well for me.

**Comment by silentpickle** [comment]
`<Measure></Measure>`

**Comment by que-etc** [comment]
Indeed, Measure component needs at least (and most) one child element: either HTMLELement or SVGElement. Otherwise there is nothing to measure.
