### ISSUE TITLE
possible to ship without resize-observer-polyfill?

### ISSUE THREAD

**Issue by klaemo** [souporserious/react-measure#38]
Hey,
thank you for this very helpful module :)

Currently react-measure requires resize-observer-polyfill...so even in browsers that support mutation observers I need to ship the polyfill (if I'm not mistaken).

Could it be instead left to the app developer to polyfill mutation observers as needed? react-measure would then need to use the mutation observer directly.

Am I missing something? What do you think about this?

**Comment by que-etc** [comment]
@klaemo I'd like to pay your attention that resize-observer-polyfill is a polyfill for the Resize Observer, not Mutation Observer.

For the time being, this API has been adopted only by Chrome and it's not enabled by default (it's a flagged feature under the #enable-experimental-web-platform-features). [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1272409) and [Safari](https://bugs.webkit.org/show_bug.cgi?id=157743) are also working on it. 

Regards.

**Comment by klaemo** [comment]
Ooops...my bad! Sorry about that, got my DOM APIs mixed up! ;)

Thanks for the clarification :)
