### ISSUE TITLE
Fails to update when surrounding DOM causes measured element to move

### ISSUE THREAD

**Issue by danielberndt** [souporserious/react-measure#39]
Have a look at [this example](https://codepen.io/anon/pen/mWWGar) and click on the orange field to start the animation.
Maybe I'm misinterpreting the scope of this component but I was expecting that the `top` property would be continuously updated here

**Comment by danielberndt** [comment]
fyi: for now I'm circumventing the issue by creating a wrapper component that calls `measure()` on a `<Measure>`-instance every 1000ms. Not ideal but good enough for my use case.

Or are there maybe some DOM-Events out there that might be more helpful in this situation?

**Comment by souporserious** [comment]
Sorry, I could see how that is confusing. React Measure only measures the component when the dimensions have changed by using a Resize Observer. The only thing I can think of for a fix is to wrap the parent in a `Measure` component, then you will know when the child's position top changes.

@que-etc any idea on how this can be solved better?

**Comment by danielberndt** [comment]
The suggested fix only really works if you recursively wrap all parents in a `Measure` component because theoretically any of these could have an effect on the elements position.
That doesn't sound too feasible. So if there was a native DOM-Event one could listen to would be great!

I'm closing the issue for now because it seems quite out of scope indeed.

**Comment by souporserious** [comment]
Sounds good. Now that I think about it, we _might_ be able to detect that change with a [Mutation Observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). I'll try and look into when I get a chance. I'd like to be able to see if any dimensions of a box model change if possible.

**Comment by lyleunderwood** [comment]
I just fell prey to this :sob: 

I feel like it's almost more confusing to provide offset when changes to it are not detected. It sets up the expectation that the user does not have to worry about detecting changes anymore.
