### ISSUE TITLE
Ability to pass className

### ISSUE THREAD

**Issue by kareemaly** [souporserious/react-measure#40]
I'm using `styled-components` and would like the ability to do something like this

```javascript
const Wrapper = styled(Measure)`
  ....
`;
```

**Comment by kareemaly** [comment]
Sorry for not testing enough before opening this issue, it looks like you are rendering the children directly and not wrapping them with a div 👍

**Comment by souporserious** [comment]
No worries! Maybe I can add some better documentation perhaps?

**Comment by kareemaly** [comment]
Yeh probably, I would expect to treat Measure like a normal component and add styling, ref, ....etc, right? ;)

**Comment by souporserious** [comment]
The idea behind it is that you can use those dimensions to affect that element, especially when using a [child function](https://github.com/souporserious/react-measure#example-usage-w-child-function) :) you can think of it as a smart component that gives you some info about the component you pass to it.
