### ISSUE TITLE
Is it possible to manually trigger a resize?

### ISSUE THREAD

**Issue by gargantuan** [souporserious/react-measure#45]
Not sure if I should ask this here, or in the [ResizeObserver project](https://github.com/WICG/ResizeObserver/blob/master/explainer.md). Let me know if I should take this question over there. 

The resize observer doesn't pick up `window.resize` events. But the dimensions object does contain `left` and `top` values, which can change independently of the width and height of the element, and will change on `window.resize`.

In my case, I'm trying to combine `react-measure` with portals to handle UI elements such as drop-downs and fly-outs which are absolutely positioned, and need to be aligned with some ancestor element that passes it's dimensions down via contexts.

However, this quickly breaks when the window is resized and parent and child positions fall out of sync. If there was some way to trigger whatever event is triggering the resize observers handler, then it would be possible to bridge the gap between `window.resize` and element resize events.

**Comment by que-etc** [comment]
@gargantuan ResizeObserver, despite of the presence of padding top/left properties in the `contentRect`, observes the content size of an element, not its position. 

It does pick up the `resize` event but triggers notification only if it resulted in changes of, roughly speaking, `getComputedStyle(element)[width/height]` values.

As for RO itself, it doesn't allow to force trigger the handler.

**Comment by souporserious** [comment]
Sorry, as @que-etc said, it does not pick up top/left changes. There is a public [`measure` method](https://github.com/souporserious/react-measure/blob/master/src/Measure.jsx#L87) that you can call to trigger the `onMeasure` callback if you know when you want to get those new dimensions.

@que-etc are you aware of any way to listen for changes on top/left?

**Comment by gargantuan** [comment]
I'm starting to work around this with a `<DimensionsContext />` component. 

Good to know about that public measure method though. I'll give that a try too. 

**Its not working yet, but I'll edit this comment if I do get it working**

```jsx

class DimensionContext extends Component { // eslint-disable-line

  state = {
    dimensions: {
      width: 0,
      top: 0,
      height: 0,
      left: 0,
      right: 0
    }
  }

  componentDidMount() {
    window.addEventListener('resize', this.handleWindowResize);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.handleWindowResize);
  }

  handleWindowResize = () => {
    const box = this.referenceDiv.getBoundingClientRect();
    const updatedDimension = {
      ...this.state.dimesions,
      top: box.top + document.documentElement.scrollTop,
      left: box.left,
    };

    this.updateChildContexts(updatedDimension);
  }

  getChildContext() {
    return {
      ancestorDimensions: this.state.dimensions
    };
  }

  updateChildContexts = (dimensions) => {
    this.setState({ dimensions });
  }

  render() {
    return (
      <div ref={(div) => { this.referenceDiv = div; }}>
        <Measure
          onMeasure={this.updateChildContexts}
        >
          {this.props.children}
        </Measure>
      </div>
    );
  }
}

DimensionContext.propTypes = {
  children: PropTypes.node.isRequired,
};

DimensionContext.childContextTypes = {
  ancestorDimensions: PropTypes.object,
};

DimensionContext.contextTypes = DimensionContext.childContextTypes;

export default DimensionContext;

```

**Comment by que-etc** [comment]
@souporserious I'm sorry, but this is not possible using only RO.

**Comment by souporserious** [comment]
@que-etc totally 🙂 I was wondering if you knew of another way that could work alongside the RO? Maybe a MutationObserver? Seems like it could get pretty heavy though 😕

**Comment by que-etc** [comment]
@souporserious Yeah, in order to track element's absolute position you would need to subscribe for the `scroll` event, apart from tracking DOM mutations.

But why do you want to conflate this data and not to limit the scope of component moving observation of position to some other library? These events seem quite conflicting to me.

**Comment by souporserious** [comment]
Totally, it's my fault for providing `top, right, bottom, left` in this library. I think that has mislead some people. But, I think it would be nice to be notified of any change of the element's box size and/or position.

**Comment by souporserious** [comment]
@que-etc I just noticed this from you https://github.com/que-etc/intersection-observer-polyfill would that solve this issue? Could possibly be a seperate component that uses that lib it seems like.

**Comment by que-etc** [comment]
@souporserious You know that I would've told you about the IntersectionObserver if it had been of any use in your case  :slightly_smiling_face:

IO doesn't notify of an every change in element's position. Instead it tells you when the position hits certain breakpoints, like when it goes off the viewport area or becomes visible in it. A quick [sample](https://jsfiddle.net/que_etc/0kw3m831/).

**Comment by souporserious** [comment]
Been thinking about this more and might split this component into two, one that handles just width/height changes and another that handles the element position.

I think if I mix the resize observer with scroll events I can fire an event when the element's position changes.

**Comment by gargantuan** [comment]
@souporserious That feels a lot neater to me.

**Comment by souporserious** [comment]
So I have an idea for getting the position. It would require two resizeObservers though :/

But.. I'm thinking we could listen for scroll events + a resize observer on the element and it's parent. That way if an element is repositioned by [an animation](https://github.com/souporserious/react-measure/issues/39) for instance, it can pick up the change.

Maybe there could be some optimizations by checking if the element already has a RO attached to it.

@que-etc @danielberndt feel free to weigh in on my crazy ideas 😅

**Comment by danielberndt** [comment]
As far as I can see, this will only work reliably if we recursively attach resize observers to all parent nodes up until the root. (I.e. my current node's position might be affected by size-changes of some node way up in the DOM, e.g. the `body` tag.)

**Comment by jrweinb** [comment]
I solved this by calling `this.refs.measureComponent.measure()`
where `measureComponent` is a ref that I assigned to the Measure Component, inside a resize listener on the window. For example:
```
<Measure 
     ref='measureComponent'
     bounds
     onResize=
     {(contentRect) => {
          this.setState({
          dimensions: contentRect.bounds,
      }); 
    }} >
```
