### ISSUE TITLE
Problem with CSS animation

### ISSUE THREAD

**Issue by abramobagnara** [souporserious/react-measure#47]
I've verified in Firefox that the dimensions passed to callback are not the final ones, but the ones at a random time during animation.
Is this expected?

**Comment by souporserious** [comment]
I believe so. This has to do with the polyfill. You can find out more about the limitations [here](https://github.com/que-etc/resize-observer-polyfill#limitations). I'm guessing you need more accurate information when an animation is running?

**Comment by abramobagnara** [comment]
It is not a matter of precision. The point is that I can't get the final size of element in this way and this is the only relevant dimension for my use case.

**Comment by souporserious** [comment]
Hmm weird. Can you provide some more details on what browser you're using as well as a sandboxed version of the bug? You can fork this [Codepen](http://codepen.io/souporserious/pen/rLdwao/) if you would like.

**Comment by que-etc** [comment]
@abramobagnara No, It's not expected though it may happen every now and then.

Could you please tell what do you mean by the final state? Are you talking about the one at the end of an iteration? As in case of an animation the final state would actually be the initial state of an element.

If that is what you need, then firing notification on the `animationend` event should do the trick and I could release a patch with it. But apart from it there is not much that could be done, I'm afraid.

**Comment by abramobagnara** [comment]
I've observed it with a react-virtualized table inside an ant design modal box.
The modal box is zoomed with a CSS transform driven animation.
I've been able to reproduce it in this [Codepen](http://codepen.io/abramo/pen/rmWeRo)

**Comment by que-etc** [comment]
@abramobagnara Oh, now I see it. This problem has nothing to do with CSS animations.

According to the [spec](https://wicg.github.io/ResizeObserver/#intro), ResizeObserver, which is internally used here, doesn't take into account CSS transformations. So it won't notify of changes when a new scale value is applied because the size of its content rectangle actually stays the same at around `176 x 300`. Try setting the width to a fixed value (~100px) and you will see that dimensions are not updated at all. 

The reason why the reported size is different form the actual content rectangle is that the Measure component, unlike RO, does reflect transformations as it uses the `getBoundingClientRect` to compute final dimensions:
```html
<div style="width: 300px; height: 300px; transform: scale(0.5)"></div>
<!--
getBoundingClientRect/Measure: {width: 150px, height: 150px}
ResizeObserver: {width: 300px, height: 300px}
-->
```

**Comment by abramobagnara** [comment]
@que-etc Your comment seems to no reflect what is observed: if indeed this component use ResizeObserver and indeed ResizeObserver don't take in account transform we should not get wrong dimensions in the Codepen, but we would get always height = 300 (while this is not the case).

Do we agree that the fact that react-measure get dimensions in an random time of transform animation but it does not listen the further change of such dimensions should be considered a bug?

I'd say that either it is able to listen the dimensions changes during animation of transform or it should get the dimensions not considering the transform.

**Comment by abramobagnara** [comment]
@que-etc In fact react-measure use ResizeObserver to trigger the measurement but it uses getBoundClientRect to measure. This explain well what we observe: in short the trigger and the measurer are related to different/incongruent dimensions.

**Comment by que-etc** [comment]
@abramobagnara 
> the Measure component, unlike RO, does reflect transformations as it uses the getBoundingClientRect to compute final dimensions

Yeah, I've mentioned this fact. I'm sorry for not being clear.

**Comment by souporserious** [comment]
Ahhh I see what's going on now. I'm going to work on a small rewrite soon. @abramobagnara maybe we can an different dimensions like scrollWidth, offsetWidth, etc. Maybe the `whitelist` prop could be used like `whitelist={['offsetWidth', 'offsetHeight']}` and you would only get those back when a change was detected. Does that make sense?

**Comment by abramobagnara** [comment]
Yes, to have also other dimensions might be a solution. Said that I see little point to retrieve dimension whose change is not observed by ResizeObserver like the ones from getBoundClientRect: it seems an honey pot trap for module users ;-) Isn't better to retrieve and pass only the same dimensions that ResizeObserver tracks?

**Comment by souporserious** [comment]
Yes this is totally true, and unfortunately I didn't realize when I made this :/ yeah I think the new version should only care about width/height which could either be the offset or from getBoundingClientRect. I might even split it into two components because I think getting top, right, bottom, and left can be useful.

**Comment by abramobagnara** [comment]
Have you considered to simply use the dimensions that ResizeObserver passes to listener?

**Comment by souporserious** [comment]
Ah yes! Most definitely :) when this library was first made it relied on other ways to get the dimensions. Didn't realize the Resize Observer provides those details already.

**Comment by souporserious** [comment]
In the latest release [the entry](https://github.com/souporserious/react-measure/blob/master/src/with-content-rect.js#L68-L70_) is now passed in if it is available :)
