### ISSUE TITLE
Detect if component is clone?

### ISSUE THREAD

**Issue by chen-ye** [souporserious/react-measure#5]
Is there any way for a component to detect if it is a clone?  I'm animating a form using react-motion-ui-pack, which sets input focus when it's created.  But when react-measure clones the form, it attempts to focus on the cloned input.  This is undesirable.

**Comment by souporserious** [comment]
No there is not. Cloning is a pain. I'm working on getting rid of cloning all together. I'll keep this open until I get something out. I'll try and push out a patch to fix that though so you don't have to wait. Are you using a ref to get the form and set focus?

**Comment by souporserious** [comment]
Cloning has been removed in the latest release https://github.com/souporserious/react-measure/commit/f1fd47b729c17469e46af8ec019f34a6bc95b7f0 I will update the UI pack as soon as I get a chance, which should fix your problem :)

**Comment by chen-ye** [comment]
awesome! Thanks!
