### ISSUE TITLE
add Flow

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-measure#55]
I like types. I think other people like types. Let's add Flow to this thing. Feel free to PR if you see this and would like to help 😄

**Comment by TrySound** [comment]
Would you like to rewrite code on flow instead of prop types or just add flow typings?

**Comment by souporserious** [comment]
I was thinking of replacing PropTypes with Flow and using [babel-plugin-react-flow-props-to-prop-types](https://github.com/thejameskyle/babel-plugin-react-flow-props-to-prop-types).
