### ISSUE TITLE
Only works on native DOM elements

### ISSUE THREAD

**Issue by Philipp91** [souporserious/react-measure#57]
Unlike with 1.x, `react-measure` version 2.x only allows measuring elements like `<div>`s, but not other React components, because their refs are not elements and thus cannot be passed into the resize observer's `observe(target: Element)` function (https://github.com/souporserious/react-measure/blob/master/src/with-content-rect.js#L56).

Is there a workaround for that?

**Comment by souporserious** [comment]
This is true. You will need access to the components ref. You can get around this by doing the something like the following:

```js
function MyComponent({ innerRef, ...props }) {
  return <div ref={innerRef} {...props}/>
}

const App = () => (
  <Measure>
    {({ measureRef }) => <MyComponent innerRef={measureRef}/>}
  </Measure>
)
```

Unfortunately, you might have to file an issue with a library author if they don't expose this for you.

You _might_ be able to do something like this (untested):

```js
<Measure>
  {({ measureRef }) => (
    <MyComponent ref={c => measureRef(ReactDOM.findDOMNode(c))} />
  )}
</Measure>
```

**Comment by chrisdrackett** [comment]
@souporserious this seems like a fairly big issue when it comes to deeply nested react components, especially if some of the components are not owned by me. I'm still testing 2.0, but so far its been a bit painful :)

**Comment by souporserious** [comment]
Sorry about that 😕 In order to allow testing of this component I think it has to be this way. I'm open to any ideas if we can get testing and `findDOMNode` to play nice. Did the above not work for you?

**Comment by chrisdrackett** [comment]
not sure, going to give it a go once I get out of meetings :D

**Comment by souporserious** [comment]
Awesome, would love to know if it works or not 😊

**Comment by chrisdrackett** [comment]
I'm probably also having an issue due to functional components. It is too bad there isn't a better way to handle these usecases in react! :) (that I've found yet)

**Comment by chrisdrackett** [comment]
anyways, I got this working using innerRef (or similar) so thats good, I'm on 2.0!
