### ISSUE TITLE
Fix build for bower

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-measure#6]
Right now shallowCompare is not exposed correctly for bower https://github.com/souporserious/react-measure/blob/master/webpack.prod.config.js#L29 need to replace with this https://www.npmjs.com/package/react-addons-shallow-compare

**Comment by souporserious** [comment]
Kind of fixed https://github.com/souporserious/react-measure/commit/44c1f1fb6c57bc7e7072ab290cf292298f9c2614 need to figure out how to not bundle it with dist but still allow its use.

**Comment by frederickfogerty** [comment]
Not sure what's wrong with your solution, this is the webpack way to do it. If you leave [this](https://github.com/souporserious/react-measure/commit/44c1f1fb6c57bc7e7072ab290cf292298f9c2614#diff-1a19ad1ad8c7b53ba23a02dcba546ee8L29) in for the build, it won't bundle it in.

https://webpack.github.io/docs/library-and-externals.html
