### ISSUE TITLE
Bring cloning back

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-measure#67]
Cloning was removed in 2.0.0, but I think it would be beneficial to bring it back. Before, we cloned the node in an external library, but we might get some benefits by letting React doing the cloning. I think this should be a method on `withContentRect` or maybe a seperate utility that will take the component, clone it, then remove it and return the new dimensions. [This article](https://css-tricks.com/snippets/jquery/animate-heightwidth-to-auto/) inspired me to bring it back 😇

**Comment by robwise** [comment]
Do you think doing this would also end up resolving #53 ?
