### ISSUE TITLE
Image detection

### ISSUE THREAD

**Issue by juhaelee** [souporserious/react-measure#7]
Is it possible for react-measure to give back changing heights for a div that only contains a image? I get back a height that is always less than the actual height whenever I resize the browser. I'm guessing this is because that it measures before the image is loaded?

**Comment by souporserious** [comment]
I have not tested with images yet, I will see what I can do. Thank you for the feedback.

**Comment by souporserious** [comment]
Closing this, I'd rather leave image implementation to the user. You could use [Image Events](https://facebook.github.io/react/docs/events.html#image-events) to tell when the image is loaded then use `shouldMeasure` to measure the content when you know the image has loaded.

**Comment by MatthewKosloski** [comment]
Hey, I tried using the `onLoad` Image Event  to detect when the image has loaded, but I didn't get satisfactory results.  Essentially what I've done is when the image has loaded (`handleImageLoaded()` has been called), change the `hasLoaded` state property to `true`.

Here is a [video demo](https://cl.ly/250M2g3X1k21).

Here is the code:

```
import React, {Component} from 'react';
import Measure from '../src/react-measure';
class AtomicImage extends Component {

    constructor() {
        super();
        this.state = {
            hasLoaded: false,
            dimensions: {}
        };
        this.onMeasure = this.onMeasure.bind(this);
        this.handleImageLoaded = this.handleImageLoaded.bind(this);
    }

    onMeasure(dimensions) {
        this.setState({dimensions});
    }

    handleImageLoaded() {
        this.setState({hasLoaded: true});
    }

    render() {

        const {src} = this.props;
        const {hasLoaded, dimensions} = this.state;
        const {width, height} = dimensions;

        return(
            <div>
                <p>Dimensions: {width} x {height}</p>
                <p>Image Loaded: {hasLoaded ? 'true' : 'false'}</p>
                <Measure onMeasure={this.onMeasure} shouldMeasure={hasLoaded === true}>
                    <div style={{display: 'inline-block'}}>
                        <img src={src} onLoad={this.handleImageLoaded}/>
                    </div>
                </Measure>
            </div>
        );
    }
}

export default AtomicImage;
```

Here is the parent code.  It's not really important—just passes `src` to the `AtomicImage` element:

```
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import AtomicImage from './AtomicImage';

class App extends Component {

  constructor() {
    super();
    this.state = {src: ''}
    this.handleOnChange = this.handleOnChange.bind(this);
  }

  handleOnChange(e) {
    this.setState({src: e.target.value});
  }

  render() {

    const {src} = this.state;
    return (
      <div>
        <div>
          <input onChange={this.handleOnChange} type="text"/>
        </div>
        <AtomicImage src={src} />
      </div>
    )
  }

}

ReactDOM.render(<App />, document.getElementById('app'));
```

**Comment by MatthewKosloski** [comment]
Hey, sorry to bother you again, but I'm really confused.  It only works when the images are cached? (again, I'm using the same code as above):

[Here is a demo](https://cl.ly/350b3f0O1l1G)
