### ISSUE TITLE
Cannot use ref within <Measure>

### ISSUE THREAD

**Issue by estaub** [souporserious/react-measure#71]
Refs worked in V1, but break in V2 with React error: 

`Stateless function components cannot have refs.`

Example:
```tsx
<Measure bounds onResize={...}>
    {() => (
        <div ref='outerDiv' className={css(styles.outerDiv)}></div>
    )}
</Measure>
```

**Comment by souporserious** [comment]
String refs unfortunately don't work with child functions. You can read more about them [here](https://github.com/chenglou/react-motion#faq). I'll add the same documentation here when I get a chance.
