### ISSUE TITLE
React-Measure does not work on elements in another window

### ISSUE THREAD

**Issue by marchaos** [souporserious/react-measure#72]
This is because of this issue: https://github.com/que-etc/resize-observer-polyfill/issues/17

I'm slightly concerned since the guy maintaining resize-observer-polyfill hasn't been active for some time.

**Comment by marchaos** [comment]
#https://github.com/que-etc/resize-observer-polyfill/issues/17

**Comment by souporserious** [comment]
Looks like this has been fixed or at least slightly fixed now.

**Comment by marchaos** [comment]
Yep. Cheers

**Comment by merraysy** [comment]
How did you fix this?
