### ISSUE TITLE
Remove children: PropTypes.func in withContentRect()

### ISSUE THREAD

**Issue by jpolo** [souporserious/react-measure#75]
This prop typing is only valid for <Measure> component. I use withContentRect() with a component (successfully) and the type of children is a regular react-fragment

**Comment by dkrieger** [comment]
I agree that children shouldn't need to be a function. currently doing `{(arg) => <Child prop={arg} />}` to work around this, but I think there are more performant ways of rendering children dynamically at this point in react

**Comment by joekrill** [comment]
I'd like to see this as well. I'm using `recompose` and it gives me a warning when I try to compose `withContentRect()` -- unless it's the last higher-order component I compose and I use the workaround that @dkrieger mentioned. I'll throw up a quick PR for it.
