### ISSUE TITLE
Please tag v2 as `latest` on npm

### ISSUE THREAD

**Issue by jstcki** [souporserious/react-measure#99]
Currently, v3.0.0-rc.3 is tagged as `latest` on npm, which is still WIP and undocumented judging from the README. But since it's `latest`, `npm install react-measure` will install that version instead of v2.

Thanks in advance!

**Comment by souporserious** [comment]
Sorry about that! I've been wanting to do something like this, but don't know how 😓. Do you by chance know how to do this? I haven't found anything online to be able to point back to an old version on NPM.

**Comment by jstcki** [comment]
`npm dist-tag add react-measure@2.0.2 latest`

With `npm dist-tag ls react-measure` you can check if it worked.

When publishing prerelease versions you can do something like `npm publish --tag next`

See https://docs.npmjs.com/getting-started/using-tags

**Comment by jstcki** [comment]
I have a script which helps me not to forget tagging a release; it checks if the version number contains a `-` and then will publish with tag `next` automatically: https://github.com/interactivethings/catalog/blob/master/scripts/publish#L1-L26

**Comment by souporserious** [comment]
Awesome, thank you for the tips and tricks ✨. It should be fixed!  I think I understand tags a little better now 😅. I appreciate the help 🙏.
